export const images = {
  auth: "/assets/auth.png",
  login: "/assets/login.png",
  Logo: "/assets/Logo.png",
  addnewicon: "/assets/addnewicon.svg",
  complainticon: "/assets/complainticon.svg",
  completedicon: "/assets/completedicon.svg",
  managecomplainticon: "/assets/managecomplainticon.svg",
  pending: "/assets/pending.svg",
  processingicon: "/assets/processingicon.svg",
  mangetemicon: "/assets/mangetemicon.svg",
  workingicon: "/assets/workingicon.svg",
  customerPng: "/assets/customerCarePNG.jpg",
  registeringComplaint: "/assets/complaintregisterpng.png",
  trackingComplaint: "/assets/TrackingComplaint.png",
  Spinner: "/assets/Spinner.svg",
  ComplaintRegisteration: "/assets/ComplaintRegisteration.png",
  customerCarePNG: "/assets/customerCarePNG.jpg",
};
